import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

public class Main {
    public static byte[] getSHA(String input) throws NoSuchAlgorithmException
    {
        // Static getInstance method is called with hashing SHA
        MessageDigest md = MessageDigest.getInstance("SHA-256");

        // digest() method called
        // to calculate message digest of an input
        // and return array of byte
        return md.digest(input.getBytes(StandardCharsets.UTF_8));
    }

    public static String toHexString(byte[] hash)
    {
        // Convert byte array into signum representation
        BigInteger number = new BigInteger(1, hash);

        // Convert message digest into hex value
        StringBuilder hexString = new StringBuilder(number.toString(16));

        // Pad with leading zeros
        while (hexString.length() < 32)
        {
            hexString.insert(0, '0');
        }

        return hexString.toString();
    }

    public static void main(String[] args) {
        try {
            File hashes = new File("Hashes.txt");
            if (hashes.createNewFile()){
                System.out.println("New File Created: " + hashes.getName());
            }else {
                System.out.println("File Already Exists");
            }
        } catch (IOException e){
            System.out.println("Some Error has occured");
            e.printStackTrace();
        }
        try
        {
//            System.out.println("HashCode Generated by SHA-256 for:");
            FileWriter fileWriter = new FileWriter("Hashes.txt");
            StringBuilder sb = new StringBuilder("shreyansjain");
//            while(true){
//                Scanner sc = new Scanner(System.in);
//                System.out.println("Enter");
//                String x = sc.nextLine();
//
//                System.out.println("\n" + x + " : " + toHexString(getSHA(x)));
//                System.out.print("Exit?");
//                if(sc.nextInt() == 1)break;
//            }
            String alpha = "abcdefghijklmnopqrstuvwxyz";
            for(int i = 0; i < 26; i++){
                sb.append(alpha.charAt(i));
                String sha = toHexString(getSHA(sb.toString()));
                fileWriter.write(sb.toString() + "    " + sha);
                sb.deleteCharAt(sb.length()-1);
            }
            // String s1 = "GeeksForGeeks";
            // System.out.println("\n" + s1 + " : " + toHexString(getSHA(s1)));

            // String s2 = "hello world";
            // System.out.println("\n" + s2 + " : " + toHexString(getSHA(s2)));
        }
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            System.out.println("Exception thrown for incorrect algorithm: " + e);
        } catch (IOException e){
            //Exception handler for fileWriter
            System.out.println("An error occurred with the fileWriter");
        }

        System.out.println("Program execution complete. :)");
    }
}
